"""Ошовлення стовпчику з адресом самокату

Revision ID: 7ab5cbcf6432
Revises: 033ed0cb5929
Create Date: 2026-09-02 10:37:09.719760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab5cbcf6432'
down_revision: Union[str, Sequence[str], None] = '033ed0cb5929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('address', sa.String(length=200), nullable=False))
    op.drop_column('stations', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('adress', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('stations', 'address')
    # ### end Alembic commands ###
