"""Створено таблицю з поїздками

Revision ID: c2033b15fa6e
Revises: d52f7897f71f
Create Date: 2026-09-03 13:23:55.509583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2033b15fa6e'
down_revision: Union[str, Sequence[str], None] = 'd52f7897f71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_ride', sa.Date(), nullable=False),
    sa.Column('end_ride', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='statusride'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('scooter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scooter_id'], ['scooters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rides')
    # ### end Alembic commands ###
