"""empty message

Revision ID: d7d7fb576d55
Revises: c2033b15fa6e
Create Date: 2026-09-03 13:36:48.013471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d7fb576d55'
down_revision: Union[str, Sequence[str], None] = 'c2033b15fa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'end_ride',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'end_ride',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
