"""empty message

Revision ID: e5e27e547886
Revises: d7d7fb576d55
Create Date: 2026-09-04 08:44:23.288137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e27e547886'
down_revision: Union[str, Sequence[str], None] = 'd7d7fb576d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooters', sa.Column('price', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scooters', 'price')
    # ### end Alembic commands ###
